library(dplyr)
library(readxl)
library(stringr)
data <- readxl::read_xlsx('041624_PTPA_Responses.xlsx') %>% data.frame()
#escape apostrophes that may be found in the Excel data; this will mess up SQL
data <- data.frame(lapply(data, function(x) {
  gsub("'","''",x)
}))

data <- data %>% dplyr::arrange(Start.Date)

data <- data %>% mutate(jurisdiction_id = case_when(
  Respondent.ID == 114539706242 ~ 45,
  Respondent.ID == 114531145936 ~ 49,
  Respondent.ID == 114528657948 ~ 66,
  Respondent.ID == 114526904884 ~ 44,
  Respondent.ID == 114519901647 ~ 8,
  Respondent.ID == 114501089919 ~ 58,
  Respondent.ID == 114499189343 ~ 67,
  Respondent.ID == 114499180680 ~ 34,
  Respondent.ID == 114499171338 ~ 1,
  Respondent.ID == 114499135809 ~ 15,
  Respondent.ID == 114499124159 ~ 61,
  Respondent.ID == 114499123114 ~ 14,
  Respondent.ID == 114499108393 ~ 39,
  Respondent.ID == 114499055706 ~ 48,
  Respondent.ID == 114493814576 ~ 68,
  Respondent.ID == 114493802232 ~ 64,
  Respondent.ID == 114493784233 ~ 56,
  Respondent.ID == 114493684392 ~ 4,
  Respondent.ID == 114492783374 ~ 22,
  Respondent.ID == 114492764229 ~ 42,
  Respondent.ID == 114488212930 ~ 5,
  Respondent.ID == 114488136775 ~ 53,
  Respondent.ID == 114481970216 ~ 18,
  Respondent.ID == 114464461063 ~ 3,
  Respondent.ID == 114475460755 ~ 2,
  Respondent.ID == 114474180505 ~ 45,
  Respondent.ID == 114427148888 ~ 69,
  Respondent.ID == 114469329225 ~ 10,
  Respondent.ID == 114466868046 ~ 70,
  Respondent.ID == 114465962170 ~ 28,
  Respondent.ID == 114462303924 ~ 27,
  Respondent.ID == 114461883794 ~ 71,
  Respondent.ID == 114459146195 ~ 70,
  Respondent.ID == 114454039408 ~ 9,
  Respondent.ID == 114454847367 ~ 72,
  Respondent.ID == 114442462939 ~ 38,
  Respondent.ID == 114457273759 ~ 9,
  Respondent.ID == 114449559999 ~ 73,
  Respondent.ID == 114451745202 ~ 43,
  Respondent.ID == 114447220479 ~ 25,
  Respondent.ID == 114445275103 ~ 17,
  Respondent.ID == 114446304636 ~ 7,
  Respondent.ID == 114493802232 ~ 64,
  Respondent.ID == 114493814576 ~ 68,
  Respondent.ID == 114445038039 ~ 46,
  Respondent.ID == 114444388932 ~ 74,
  Respondent.ID == 114444214711 ~ 11,
  Respondent.ID == 114444136044 ~ 24,
  Respondent.ID == 114443881903 ~ 26,
  Respondent.ID == 114441444545 ~ 52,
  Respondent.ID == 114433800975 ~ 55,
  Respondent.ID == 114441493075 ~ 37,
  Respondent.ID == 114438952760 ~ 35,
  Respondent.ID == 114493784233 ~ 56,
  Respondent.ID == 114437800107 ~ 31,
  Respondent.ID == 114499180680 ~ 34,
  Respondent.ID == 114435867816 ~ 75,
  Respondent.ID == 114449559999 ~ 73, #ALREADY captured
  Respondent.ID == 114430684879 ~ 21, #ID does not exist?
  Respondent.ID == 114430421428 ~ 40,
  Respondent.ID == 114466868046 ~ 70,
  Respondent.ID == 114427409265 ~ 13,
  Respondent.ID == 114499189343 ~ 67,
  Respondent.ID == 114428402375 ~ 41,
  Respondent.ID == 114428378146 ~ 16,
  Respondent.ID == 114427908795 ~ 54,
  Respondent.ID == 114427479403 ~ 51,
  Respondent.ID == 114427412004 ~ 76,
  Respondent.ID == 114542568363 ~ 6,
  Respondent.ID == 114578514782 ~ 14,
  Respondent.ID == 114567064753 ~ 21,
  Respondent.ID == 114578645759 ~ 23,
  Respondent.ID == 114567083617 ~ 27,
  Respondent.ID == 114544497390 ~ 29,
  Respondent.ID == 114565518891 ~ 30,
  Respondent.ID == 114573294291 ~ 32,
  Respondent.ID == 114573275060 ~ 33,
  Respondent.ID == 114546419581 ~ 44,
  Respondent.ID == 114554192485 ~ 44,
  Respondent.ID == 114570863934 ~ 54,
  Respondent.ID == 114570732691 ~ 65,
  Respondent.ID == 114564515361 ~ 63,
  Respondent.ID == 114553829962 ~ 77,
  Respondent.ID == 114430142765 ~ 68,
  Respondent.ID == 114434810712 ~ 73,
  Respondent.ID == 114539993093 ~ 20
  )
)
need_jurisdiction_IDs <- data %>% filter(is.na(jurisdiction_id)) %>% filter(!is.na(Respondent.ID))
print('Script will halt if we have not assigned jursidiction IDs to all survey data')
stopifnot(nrow(need_jurisdiction_IDs) == 0)
print('All survey responses have been assigned a jurisdiction_id')

# Calculate the max start date per jurisdiction ID - consider this, being the most recent submission, as the best data. 
maxStartDates <- data %>% dplyr::group_by(jurisdiction_id) %>% dplyr::summarise(Start.Date = max(Start.Date))
# Inner join on the jurisdiction IDs and max start dates to grab the 'best data'
data <- data %>% dplyr::inner_join(maxStartDates, by = c('jurisdiction_id', 'Start.Date'))

#create SQL generation function based on data structure
#____ note: we will need to change for loops from 2:nrow to 1:nrow if we remove the first row "header"
generateSql <- function(dataset, qnum, colnum, category, subQ) {
  category2 <- ifelse(category == '' , 'NULL',category)
  subQ2 <- ifelse(subQ == '', 'NULL',subQ)
  # start at row 2 because row 1 doesnt represent a real response
  for (row in 2:nrow(dataset)) {
    cat(paste0("(2, ", 2000+row, ", 2023, ",qnum, ", ", category2, ", ", 
               subQ2,", '", dataset[row,colnum], "'),\n"))#, quote = F)
  }                
}

generateSqlMerge <- function(dataset, qnum, colnum, colnumTotal, category, subQ) {
  category2 <- ifelse(category == '' , 'NULL',category)
  subQ2 <- ifelse(subQ == '', 'NULL',subQ)
  colnumCounter <- colnumTotal - 1 # if we have 3 columns that we want to capture, we would set colnumTotal = 3 in function. We then would choose columns starting at colnum and ending at colnum+(colnumTotal-1). i.e., if columns #144-146 are trying to be merged, there are 3 total columns, and our column subsetting properly reflects [,144:146].
  # start at row 2 because row 1 doesnt represent a real response
  for (row in 2:nrow(dataset)) {
    # combinedResponse <- paste(as.character(dataset[row,colnum:colnum+colnumCounter]),collapse=",", sep = ",")
    values <- apply(dataset[row, colnum:(colnum + colnumCounter)], 1, function(x) ifelse(is.na(x), "", as.character(x)))
    combinedResponse <- paste(values, collapse = ",")
    # Replace consecutive commas with a single comma
    combinedResponse <- gsub(",{2,}", ",", combinedResponse)
    
    # Remove any leading or trailing commas
    combinedResponse <- gsub("^,|,$", "", combinedResponse)
    
    
    cat(paste0("(2, ", 2000+row, ", 2023, ",qnum, ", ", category2, ", ", 
               subQ2,", '", combinedResponse, "'),\n"))#, quote = F)
  }                
}

# generateSqlMerge(data, 13, 142, 3, '', '')

#assign each unique jurisdicton a specific ID first, mutate a column to be that ID, reference that column wrt the response given so that we handle duplicates / or just delete the incorrect DUPES of primary response

# Open text file, write function output into it without R idiosyncrasies forcing us to use text replace
### had to add the multiple insert into statements to avoid sql server limit of 1000 inserts. also, one must manually remove the final comma in the last set of values before the next "insert into" statement. I think we may need to insert into SQL pre-tabularized data, or come up with something more elegant.
### NOTEPAD++ allows for replace over multiple lines, therefore can replace the phrase ",INSERT INTO" and remove the preceding commas for mass insert.
sink("insertResponsesDetailed2023.txt") 
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 10, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 11, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 12, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 13, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 2, 14, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 3, 15, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 4, 17, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ') 
generateSql(data, 5, 18, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 5, 19, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 5, 20, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 6, 21, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 6, 22, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 7, 23, '' , '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 24, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 25, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 26, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 27, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 28, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 29, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 30, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 31, 4, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 35, 4, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 39, 4, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 43, 4, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 47, 4, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 51, 4, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 9, 55, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 56, 4, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 60, 4, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 64, 4, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 68, 4, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 72, 4, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 76, 4, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 80, 4, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 84, 4, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 88, 4, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 92, 4, '' , 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 96, 4, '' , 11)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 100, 4, '' , 12)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 104, 4, '' , 13)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 108, 4, '' , 14)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 112, 4, '' , 15)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 116, 4, '' , 16)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 120, 4, '' , 17)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 10, 124, '' , 18)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 125, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 126, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 127, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 128, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 129, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 130, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 131, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 132, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 133, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 134, '' , 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 135, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 136, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 137, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 138, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 139, 3, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 142, 3, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 145, 3, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 148, 3, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 151, 3, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 154, 3, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 157, 3, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 160, 3, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 163, 3, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 166, 3, '' , 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 169, 3, '' , 11)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 172, 3, '' , 12)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 175, 3, '' , 13)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 178, 3, '' , 14)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 181, 3, '' , 15)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 184, 3, '' , 16)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 187, 3, '' , 17)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 190, 3, '' , 18)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 193, 3, '' , 19)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 196, 3, '' , 20)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 13, 199, '' , 21)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 200, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 201, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 202, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 203, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 204, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 205, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 206, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 207, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 208, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 16, 209, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 16, 210, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 16, 211, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 17, 212, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 17, 213, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 18, 214, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 18, 215, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 18, 216, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 18, 217, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 18, 218, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 18, 219, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 19, 220, 3, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 19, 223, 3, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 19, 226, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 20, 227, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 20, 228, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 20, 229, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 20, 230, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 20, 231, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 232, 3, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 235, 3, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 238, 3, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 241, 3, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 244, 3, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 247, 3, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 250, 3, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 253, 3, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 21, 256, 3, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 21, 259, '', 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 22, 260, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 22, 261, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 23, 262, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 23, 263, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 24, 264, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 24, 265, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 25, 266, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 25, 267, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 268, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 269, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 270, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 271, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 272, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 273, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 274, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 275, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 26, 276, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 27, 277, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 28, 278, 2, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 28, 280, 2, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 28, 282, 2, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 28, 284, 2, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 29, 286, 2, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 29, 288, 2, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 29, 290, 2, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 29, 292, 2, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 29, 294, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 30, 295, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 30, 296, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 31, 297, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 31, 298, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 32, 299, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 32, 300, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 33, 301, 3, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 33, 304, 3, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 33, 307, 3, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 34, 310, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 34, 311, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 34, 312, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 35, 313,3, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 35, 316,3, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 35, 319,3, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 35, 322,3, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 35, 325, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 36, 326, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 36, 327, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 36, 328, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 36, 329, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 36, 330, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 37, 331, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 37, 332, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 37, 333, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 37, 334, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 37, 335, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 37, 336, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 38, 337, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 38, 338, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 339, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 340, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 341, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 342, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 343, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 344, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 345, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 39, 346, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 347, 1, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 348, 1, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 349, 1, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 350, 1, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 351, 2, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 352, 2, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 353, 2, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 354, 2, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 355, 3, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 356, 3, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 357, 3, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 358, 3, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 359, 4, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 360, 4, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 361, 4, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 362, 4, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 363, 5, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 364, 5, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 365, 5, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 366, 5, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 367, 6, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 368, 6, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 369, 6, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 370, 6, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 371, 7, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 372, 7, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 373, 7, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 374, 7, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 375, 8, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 376, 8, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 377, 8, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 378, 8, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 379, 9, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 380, 9, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 381, 9, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 382, 9, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 383, 10, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 384, 10, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 385, 10, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 386, 10, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 387, 11, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 388, 11, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 389, 11, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 390, 11, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 391, 12, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 392, 12, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 393, 12, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 394, 12, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 395, 13, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 396, 13, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 397, 13, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 398, 13, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 399, 14, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 400, 14, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 401, 14, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 402, 14, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 403, 15, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 404, 15, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 405, 15, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 406, 15, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 407, 16, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 408, 16, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 409, 16, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 410, 16, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 411, 17, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 412, 17, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 413, 17, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 414, 17, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 415, 18, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 416, 18, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 417, 18, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 418, 18, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 419, 19, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 420, 19, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 421, 19, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 422, 19, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 423, 20, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 424, 20, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 425, 20, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 426, 20, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 427, 21, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 428, 21, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 429, 21, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 430, 21, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 431, 22, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 432, 22, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 433, 22, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 434, 22, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 435, 23, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 436, 23, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 437, 23, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 438, 23, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 439, 24, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 440, 24, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 441, 24, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 442, 24, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 443, 25, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 444, 25, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 445, 25, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 446, 25, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 447, 26, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 448, 26, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 449, 26, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 450, 26, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 451, 27, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 452, 27, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 453, 27, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 454, 27, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 455, 28, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 456, 28, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 457, 28, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 458, 28, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 459, 29, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 460, 29, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 461, 29, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 462, 29, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 463, 30, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 464, 30, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 465, 30, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 466, 30, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 467, 31, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 468, 31, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 469, 31, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 470, 31, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 471, 32, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 472, 32, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 473, 32, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 474, 32, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 40, 475, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 41, 476, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 42, 477, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 42, 478, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 43, 479, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 43, 480, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 43, 481, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 44, 482, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 44, 483, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 44, 484, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 44, 485, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 44, 486, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 44, 487, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 45, 488, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 45, 489, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 45, 490, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 45, 491, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 45, 492, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 45, 493, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 494, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 495, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 496, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 497, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 498, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 499, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 46, 500, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 501, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 502, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 503, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 504, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 505, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 506, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 507, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 508, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 47, 509, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 48, 510, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 48, 511, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 512, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 513, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 514, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 515, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 516, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 517, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 518, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 519, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 49, 520, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 50, 521, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 50, 522, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 523, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 524, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 525, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 526, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 527, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 528, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 529, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 530, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 51, 531, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 52, 532, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 52, 533, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 53, 534, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 535, 1, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 536, 1, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 537, 1, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 538, 1, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 539, 1, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 540, 1, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 541, 1, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 542, 1, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 543, 2, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 544, 2, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 545, 2, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 546, 2, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 547, 2, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 548, 2, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 549, 2, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 550, 2, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 551, 3, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 552, 3, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 553, 3, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 554, 3, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 555, 3, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 556, 3, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 557, 3, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 558, 3, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 559, 4, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 560, 4, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 561, 4, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 562, 4, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 563, 4, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 564, 4, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 565, 4, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 566, 4, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 567, 5, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 568, 5, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 569, 5, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 570, 5, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 571, 5, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 572, 5, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 573, 5, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 574, 5, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 575, 6, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 576, 6, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 577, 6, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 578, 6, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 579, 6, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 580, 6, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 581, 6, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 582, 6, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 54, 583 ,'', 9)


cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 584, 1, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 585, 1, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 586, 1, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 587, 1, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 588, 1, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 589, 1, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 590, 1, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 591, 1, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 592, 2, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 593, 2, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 594, 2, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 595, 2, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 596, 2, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 597, 2, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 598, 2, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 599, 2, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 600, 3, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 601, 3, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 602, 3, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 603, 3, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 604, 3, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 605, 3, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 606, 3, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 607, 3, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 608, 4, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 609, 4, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 610, 4, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 611, 4, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 612, 4, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 613, 4, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 614, 4, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 615, 4, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 616, 5, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 617, 5, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 618, 5, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 619, 5, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 620, 5, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 621, 5, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 622, 5, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 623, 5, 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 55, 624, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 56, 625, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 626, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 627, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 628, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 629, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 630, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 631, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 632, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 633, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 57, 634, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 635, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 636, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 637, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 638, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 639, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 640, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 641, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 642, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 58, 643, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 644, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 645, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 646, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 647, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 648, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 649, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 650, '', 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 651, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 652, '', 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 59, 653, '', 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 60, 654, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 60, 655, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 60, 656, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 657, 1, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 658, 1, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 659, 1, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 660, 1, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 661, 1, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 662, 1, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 663, 1, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 664, 2, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 665, 2, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 666, 2, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 667, 2, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 668, 2, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 669, 2, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 670, 2, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 61, 671, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 62, 672, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 62, 673, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 62, 674, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 62, 675, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 62, 676, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 63, 677, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 63, 678, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 64, 679, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 65, 680, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 66, 681, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 66, 682, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 67, 683, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 67, 684, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 67, 685, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 67, 686, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 67, 687, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 67, 688, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 68, 689, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 68, 690, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 691, 1, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 692, 1, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 693, 1, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 694, 1, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 695, 1, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 696, 1, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 697, 1, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 698, 2, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 699, 2, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 700, 2, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 701, 2, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 702, 2, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 703, 2, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 704, 2, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 705, 3, 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 706, 3, 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 707, 3, 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 708, 3, 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 709, 3, 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 710, 3, 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 711, 3, 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 69, 712, '', 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 70, 713, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 70, 714, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 71, 715, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 71, 716, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 72, 717, 7, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 72, 724, 7, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 72, 731, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 73, 732, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 74, 733, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 74, 734, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 75, 735, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 75, 736, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 75, 737, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 75, 738, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 75, 739, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 76, 740, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 76, 741, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 77, 742, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 77, 743, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 77, 744, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 77, 745, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 77, 746, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 78, 747, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 78, 748, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 78, 749, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 78, 750, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 78, 751, '', 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 78, 752, '', 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 79, 753, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 79, 754, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 80, 755, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 80, 756, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 80, 757, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 80, 758, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 80, 759, '', 5)

sink()


generateJurisdictionToCrossSurveyID <- function(dataset, colnum) {
  # start at row 2 because row 1 doesnt represent a real response
  for (row in 1:nrow(dataset)) {
    cat(paste0("(2, ", 2000+row, ", 2023, ", dataset[row,colnum], "),\n"))#, quote = F)
  }                
}

generateJurisdictionToCrossSurveyID(data, 761)
