library(dplyr)
library(readxl)
library(stringr)
data <- readxl::read_xlsx('PTPA_Responses_2-27.xlsx') %>% data.frame()
#escape apostrophes that may be found in the Excel data; this will mess up SQL
data <- data.frame(lapply(data, function(x) {
  gsub("'","''",x)
}))
# data[is.na(data)] <- ''

#create SQL generation function based on data structure
generateSql <- function(dataset, qnum, colnum, category, subQ) {
  category2 <- ifelse(category == '' , 'NULL',category)
  subQ2 <- ifelse(subQ == '', 'NULL',subQ)
  # start at row 2 because row 1 doesnt represent a real response
  for (row in 2:nrow(dataset)) {
    cat(paste0("(2, ", 1000+row, ", 2023, ",qnum, ", ", category2, ", ", 
               subQ2,", '", dataset[row,colnum], "'),\n"))#, quote = F)
  }                
}

generateSqlMerge <- function(dataset, qnum, colnum, colnumTotal, category, subQ) {
  category2 <- ifelse(category == '' , 'NULL',category)
  subQ2 <- ifelse(subQ == '', 'NULL',subQ)
  colnumCounter <- colnumTotal - 1 # if we have 3 columns that we want to capture, we would set colnumTotal = 3 in function. We then would choose columns starting at colnum and ending at colnum+(colnumTotal-1). i.e., if columns #144-146 are trying to be merged, there are 3 total columns, and our column subsetting properly reflects [,144:146].
  # start at row 2 because row 1 doesnt represent a real response
  for (row in 2:nrow(dataset)) {
    # combinedResponse <- paste(as.character(dataset[row,colnum:colnum+colnumCounter]),collapse=",", sep = ",")
    values <- apply(dataset[row, colnum:(colnum + colnumCounter)], 1, function(x) ifelse(is.na(x), "", as.character(x)))
    combinedResponse <- paste(values, collapse = ",")
    # Replace consecutive commas with a single comma
    combinedResponse <- gsub(",{2,}", ",", combinedResponse)
    
    # Remove any leading or trailing commas
    combinedResponse <- gsub("^,|,$", "", combinedResponse)
    
    
    cat(paste0("(2, ", 1000+row, ", 2023, ",qnum, ", ", category2, ", ", 
               subQ2,", '", combinedResponse, "'),\n"))#, quote = F)
  }                
}

# generateSqlMerge(data, 13, 142, 3, '', '')

#assign each unique jurisdicton a specific ID first, mutate a column to be that ID, reference that column wrt the response given so that we handle duplicates / or just delete the incorrect DUPES of primary response

# Open text file, write function output into it without R idiosyncrasies forcing us to use text replace
### had to add the multiple insert into statements to avoid sql server limit of 1000 inserts. also, one must manually remove the final comma in the last set of values before the next "insert into" statement. I think we may need to insert into SQL pre-tabularized data, or come up with something more elegant.
### NOTEPAD++ allows for replace over multiple lines, therefore can replace the phrase ",INSERT INTO" and remove the preceding commas for mass insert.
sink("insertResponsesDetailed2023.txt") 
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 10, '', 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 11, '', 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 12, '', 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 1, 13, '', 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 2, 14, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 3, 15, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 4, 17, '', '')
cat('INSERT INTO dbo.responses_detail VALUES ') 
generateSql(data, 5, 18, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 5, 19, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 5, 20, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 6, 21, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 6, 22, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 7, 23, '' , '')
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 24, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 25, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 26, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 27, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 28, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 29, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 8, 30, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 31, 4, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 35, 4, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 39, 4, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 43, 4, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 47, 4, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 9, 51, 4, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 9, 55, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 56, 4, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 60, 4, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 64, 4, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 68, 4, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 72, 4, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 76, 4, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 80, 4, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 84, 4, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 88, 4, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 92, 4, '' , 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 96, 4, '' , 11)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 100, 4, '' , 12)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 104, 4, '' , 13)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 108, 4, '' , 14)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 112, 4, '' , 15)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 116, 4, '' , 16)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 10, 120, 4, '' , 17)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 10, 124, '' , 18)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 125, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 126, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 127, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 128, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 129, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 130, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 131, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 132, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 133, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 11, 134, '' , 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 135, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 136, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 137, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 12, 138, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 139, 3, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 142, 3, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 145, 3, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 148, 3, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 151, 3, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 154, 3, '' , 6)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 157, 3, '' , 7)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 160, 3, '' , 8)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 163, 3, '' , 9)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 166, 3, '' , 10)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 169, 3, '' , 11)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 172, 3, '' , 12)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 175, 3, '' , 13)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 178, 3, '' , 14)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 181, 3, '' , 15)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 184, 3, '' , 16)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 187, 3, '' , 17)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 190, 3, '' , 18)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 193, 3, '' , 19)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSqlMerge(data, 13, 196, 3, '' , 20)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 13, 199, '' , 21)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 200, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 201, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 202, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 14, 203, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 204, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 205, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 206, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 207, '' , 4)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 15, 208, '' , 5)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 16, 209, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 16, 210, '' , 2)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 16, 211, '' , 3)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 17, 212, '' , 1)
cat('INSERT INTO dbo.responses_detail VALUES ')
generateSql(data, 17, 213, '' , 2)

sink()
